// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtgnphsmgnkkukcfpecq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0Z25waHNtZ25ra3VrY2ZwZWNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNTgxODAsImV4cCI6MjA1NDkzNDE4MH0.4ZgT0CTu8UFwjVAIV6L-GTtQfVoqfxPHPqItvfsWymI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);